module.exports = {
    main_screen: {
        marginTop: 20,
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        width: '100%',
        height: '100%',
    },
    main_screen_display: {
        elevation: 10,
        width: '95%',
        backgroundColor: 'white',
        borderRadius: 10,
        display: 'flex',
        marginBottom: 10,
        padding: 10,
    },
    display_text: {
        fontSize: 50,
        textAlign: 'right',
    },
    main_screen_keypad: {
        width: '100%',
        height: '14%',
        display: 'flex',
    },
    keypadrow: {
        display: 'flex',
        flexDirection: 'row',
        backgroundColor: 'white',
        width: '100%',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 5,
    },
    btn1_outer: {
        width: 90,
        height: 90,
        backgroundColor: 'white',
        elevation: 10,
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 20,
        marginBottom: 15
    },
    bg1_btn: {
        // backgroundColor: 'white',
        color: 'black',
        fontSize: 30,
        borderRadius: 30,
    },
    btn1_: {
        width: 90,
        height: 90,
        backgroundColor: 'grey',
        borderRadius: 40,
        elevation: 10,
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
    },
    btn_text: {
        // backgroundColor: 'black',
        color: 'white',
        fontSize: 30,
        fontWeight: 'bold'
    },
    star: {
        color: 'white',
        fontSize: 20,
        fontWeight: 'bold',
    },
    btn_ac: {
        width: 90,
        height: 90,
        backgroundColor: '#bc4749',
        borderRadius: 80,
        elevation: 10,
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
    },
}